allData = {None: {None: {' Flow Rate': None,
               ' Flow Units': None,
               ' Pressure': None,
               'Diaphragm Material': None,
               'Diaphragm Thickness': None}},
 'BD12ANT7-NA': {'BD12ANT7-NA': {' Flow Rate': 15,
                                 ' Flow Units': 'cc/min',
                                 ' Pressure': 5,
                                 'Diaphragm Material': 'PTFE (virgin)',
                                 'Diaphragm Thickness': '5'}},
 'BD12SHT6D-NSCP60T': {'BD12SHT6D-NSCP60T': {' Flow Rate': 1.4,
                                             ' Flow Units': 'L/min',
                                             ' Pressure': 60,
                                             'Diaphragm Material': 'PGL',
                                             'Diaphragm Thickness': '10'}},
 'BD16ANT4D-NA': {'BD16ANT4D-NA': {' Flow Rate': 100,
                                   ' Flow Units': 'cc/min',
                                   ' Pressure': 5,
                                   'Diaphragm Material': 'Viton',
                                   'Diaphragm Thickness': '23'}},
 'BD16PNT4D-NP': {'BD16PNT4D-NP': {' Flow Rate': 400,
                                   ' Flow Units': 'cc/min',
                                   ' Pressure': 5,
                                   'Diaphragm Material': 'Buna',
                                   'Diaphragm Thickness': '10'}},
 'BD16SHT4M-NSCP60T': {'BD16SHT4M-NSCP60T': {' Flow Rate': 1.5,
                                             ' Flow Units': 'L/min',
                                             ' Pressure': 60,
                                             'Diaphragm Material': 'PGL',
                                             'Diaphragm Thickness': '10'}},
 'BD24SHT6C-NSCP45T': {'BD24SHT6C-NSCP45T': {' Flow Rate': 7,
                                             ' Flow Units': 'L/min',
                                             ' Pressure': 45,
                                             'Diaphragm Material': 'PGL',
                                             'Diaphragm Thickness': '10'}},
 'BD24SNT6C-N': {'BD24SNT6C-N': {' Flow Rate': 0,
                                 ' Flow Units': 'EQ',
                                 ' Pressure': 5,
                                 'Diaphragm Material': 'Viton',
                                 'Diaphragm Thickness': '23'}},
 'BD32SFT0-NSC': {'BD32SFT0-NSC': {' Flow Rate': 500,
                                   ' Flow Units': 'cc/min',
                                   ' Pressure': 5,
                                   'Diaphragm Material': 'Viton',
                                   'Diaphragm Thickness': '23'}},
 'BDM24ANT6C-N': {'BDM24ANT6C-N': {' Flow Rate': 40,
                                   ' Flow Units': 'cc/min',
                                   ' Pressure': 5,
                                   'Diaphragm Material': 'Viton',
                                   'Diaphragm Thickness': '23'}},
 'FDO16SHN1-NSCP10': {'FDO16SHN1-NSCP10': {' Flow Rate': 0,
                                           ' Flow Units': 'EQ',
                                           ' Pressure': 100,
                                           'Diaphragm Material': 'EPDM USP VI '
                                                                 '- Reinforced',
                                           'Diaphragm Thickness': '60'}},
 'FDO16SHN1-NSCP5': {'FDO16SHN1-NSCP5': {' Flow Rate': 0,
                                         ' Flow Units': 'EQ',
                                         ' Pressure': 50,
                                         'Diaphragm Material': 'EPDM USP VI - '
                                                               'Reinforced',
                                         'Diaphragm Thickness': '60'}},
 'FDO4SHD5D-NSCP1': {'FDO4SHD5D-NSCP1': {' Flow Rate': 27,
                                         ' Flow Units': 'cc/min',
                                         ' Pressure': 100,
                                         'Diaphragm Material': 'PGL',
                                         'Diaphragm Thickness': '10'}},
 'FDO4SHE5D-NSCP1': {'FDO4SHE5D-NSCP1': {' Flow Rate': 0,
                                         ' Flow Units': 'EQ',
                                         ' Pressure': 100,
                                         'Diaphragm Material': 'PTFE (virgin)',
                                         'Diaphragm Thickness': '10'}},
 'FDO4SHE5D-NSCP3': {'FDO4SHE5D-NSCP3': {' Flow Rate': 225,
                                         ' Flow Units': 'cc/min',
                                         ' Pressure': 30,
                                         'Diaphragm Material': 'PTFE - USP VI',
                                         'Diaphragm Thickness': '5'}},
 'FDO6SHN0-NSCP': {'FDO6SHN0-NSCP': {' Flow Rate': 0,
                                     ' Flow Units': 'EQ',
                                     ' Pressure': 50,
                                     'Diaphragm Material': 'Viton',
                                     'Diaphragm Thickness': '23'}},
 'FDO6SHN0-NSCP150': {'FDO6SHN0-NSCP150': {' Flow Rate': 35,
                                           ' Flow Units': 'cc/min',
                                           ' Pressure': 150,
                                           'Diaphragm Material': 'PTFE - USP '
                                                                 'VI',
                                           'Diaphragm Thickness': '15'}},
 'FDO8SHN1-NSCP': {'FDO8SHN1-NSCP': {' Flow Rate': 30,
                                     ' Flow Units': 'cc/min',
                                     ' Pressure': 50,
                                     'Diaphragm Material': 'PTFE (virgin)',
                                     'Diaphragm Thickness': '10'}},
 'FDO8SHN1-NSCP5': {'FDO8SHN1-NSCP5': {' Flow Rate': 200,
                                       ' Flow Units': 'cc/min',
                                       ' Pressure': 50,
                                       'Diaphragm Material': 'PTFE - USP VI',
                                       'Diaphragm Thickness': '10'}},
 'GS4PNG4': {'GS4PNG4': {' Flow Rate': 700,
                         ' Flow Units': 'cc/min',
                         ' Pressure': 5,
                         'Diaphragm Material': 'PTFE (virgin)',
                         'Diaphragm Thickness': '4'}},
 'GS6PNG4B': {'GS6PNG4B': {' Flow Rate': 125,
                           ' Flow Units': 'cc/min',
                           ' Pressure': 5,
                           'Diaphragm Material': 'Buna',
                           'Diaphragm Thickness': '10'}},
 'GS8SNG5-NSCP': {'GS8SNG5-NSCP': {' Flow Rate': 500,
                                   ' Flow Units': 'cc/min',
                                   ' Pressure': 15,
                                   'Diaphragm Material': 'PTFE (virgin)',
                                   'Diaphragm Thickness': '5'}},
 'GSD2ANG4-': {'GSD2ANG4-': {' Flow Rate': 1.5,
                             ' Flow Units': 'L/min',
                             ' Pressure': 5,
                             'Diaphragm Material': 'Viton',
                             'Diaphragm Thickness': '9'}},
 'GSD2ANG4-NACP200T': {'GSD2ANG4-NACP200T': {' Flow Rate': 500,
                                             ' Flow Units': 'cc/min',
                                             ' Pressure': 200,
                                             'Diaphragm Material': 'PGL',
                                             'Diaphragm Thickness': '10'}},
 'GSD2SNG4-': {'GSD2SNG4-': {' Flow Rate': 125,
                             ' Flow Units': 'cc/min',
                             ' Pressure': 5,
                             'Diaphragm Material': 'PTFE (virgin)',
                             'Diaphragm Thickness': '5'}},
 'GSD2SNG4-N': {'GSD2SNG4-N': {' Flow Rate': 1,
                               ' Flow Units': 'L/min',
                               ' Pressure': 5,
                               'Diaphragm Material': 'Viton',
                               'Diaphragm Thickness': '9'}},
 'GSD2SNG4-NSCP1': {'GSD2SNG4-NSCP1': {' Flow Rate': 1.3,
                                       ' Flow Units': '#VALUE!',
                                       ' Pressure': 1,
                                       'Diaphragm Material': 'PTFE (virgin)',
                                       'Diaphragm Thickness': '3'}},
 'GSD2SNG4-NSCP100': {'GSD2SNG4-NSCP100': {' Flow Rate': 175,
                                           ' Flow Units': 'cc/min',
                                           ' Pressure': 100,
                                           'Diaphragm Material': 'PGL',
                                           'Diaphragm Thickness': '10'}},
 'GSD2SNG4-NSCP100T': {'GSD2SNG4-NSCP100T': {' Flow Rate': 250,
                                             ' Flow Units': 'cc/min',
                                             ' Pressure': 100,
                                             'Diaphragm Material': 'PGL',
                                             'Diaphragm Thickness': '10'}},
 'GSD2SNG4-NSCP150T': {'GSD2SNG4-NSCP150T': {' Flow Rate': 18,
                                             ' Flow Units': 'cc/min',
                                             ' Pressure': 150,
                                             'Diaphragm Material': 'PGL',
                                             'Diaphragm Thickness': '10'}},
 'GSD2SNG4-NSCP3': {'GSD2SNG4-NSCP3': {' Flow Rate': 8,
                                       ' Flow Units': 'cc/min',
                                       ' Pressure': 30,
                                       'Diaphragm Material': 'Buna',
                                       'Diaphragm Thickness': '10'}},
 'GSD2SNG4-NSCP30': {'GSD2SNG4-NSCP30': {' Flow Rate': 375,
                                         ' Flow Units': 'cc/min',
                                         ' Pressure': 30,
                                         'Diaphragm Material': 'PGL',
                                         'Diaphragm Thickness': '4'}},
 'GSD2SNN4-NSCP200': {'GSD2SNN4-NSCP200': {' Flow Rate': 750,
                                           ' Flow Units': 'cc/min',
                                           ' Pressure': 200,
                                           'Diaphragm Material': 'PGL',
                                           'Diaphragm Thickness': '10'}},
 'GSD2SNN4-NSCP300': {'GSD2SNN4-NSCP300': {' Flow Rate': 140,
                                           ' Flow Units': 'cc/min',
                                           ' Pressure': 300,
                                           'Diaphragm Material': 'PGL',
                                           'Diaphragm Thickness': '10'}},
 'GSD2SNN4-NSCP300T': {'GSD2SNN4-NSCP300T': {' Flow Rate': 3,
                                             ' Flow Units': 'cc/min',
                                             ' Pressure': 300,
                                             'Diaphragm Material': 'Viton',
                                             'Diaphragm Thickness': '23'}},
 'GSD2SNN4-NSCP400T': {'GSD2SNN4-NSCP400T': {' Flow Rate': 425,
                                             ' Flow Units': 'cc/min',
                                             ' Pressure': 400,
                                             'Diaphragm Material': 'PGL',
                                             'Diaphragm Thickness': '10'}},
 'GSD2SNN4-NSMP500T': {'GSD2SNN4-NSMP500T': {' Flow Rate': 240,
                                             ' Flow Units': 'cc/min',
                                             ' Pressure': 500,
                                             'Diaphragm Material': 'PGL',
                                             'Diaphragm Thickness': '10'}},
 'GSD3PNG4B-': {'GSD3PNG4B-': {' Flow Rate': 40,
                               ' Flow Units': 'cc/min',
                               ' Pressure': 5,
                               'Diaphragm Material': 'Buna',
                               'Diaphragm Thickness': '10'}},
 'GSD3SNG4B': {'GSD3SNG4B': {' Flow Rate': 400,
                             ' Flow Units': 'cc/min',
                             ' Pressure': 5,
                             'Diaphragm Material': 'Viton',
                             'Diaphragm Thickness': '9'}},
 'GSD3SNG4B-NSCP': {'GSD3SNG4B-NSCP': {' Flow Rate': 500,
                                       ' Flow Units': 'cc/min',
                                       ' Pressure': 15,
                                       'Diaphragm Material': 'PTFE (virgin)',
                                       'Diaphragm Thickness': '5'}},
 'GSD3SNG4B-NSCP10': {'GSD3SNG4B-NSCP10': {' Flow Rate': 1,
                                           ' Flow Units': 'L/min',
                                           ' Pressure': 100,
                                           'Diaphragm Material': 'PGL',
                                           'Diaphragm Thickness': '8'}},
 'GSD3SNN4B-NSCP': {'GSD3SNN4B-NSCP': {' Flow Rate': 275,
                                       ' Flow Units': 'cc/min',
                                       ' Pressure': 50,
                                       'Diaphragm Material': 'PGL',
                                       'Diaphragm Thickness': '4'}},
 'GSD3SNN4B-NSCP25': {'GSD3SNN4B-NSCP25': {' Flow Rate': 140,
                                           ' Flow Units': 'cc/min',
                                           ' Pressure': 250,
                                           'Diaphragm Material': 'SS316',
                                           'Diaphragm Thickness': '4'}},
 'GSD3SNT4B-NSC': {'GSD3SNT4B-NSC': {' Flow Rate': 125,
                                     ' Flow Units': 'cc/min',
                                     ' Pressure': 50,
                                     'Diaphragm Material': 'PTFE (virgin)',
                                     'Diaphragm Thickness': '5'}},
 'GSD3SNT4B-NSCP': {'GSD3SNT4B-NSCP': {' Flow Rate': 25,
                                       ' Flow Units': 'cc/min',
                                       ' Pressure': 15,
                                       'Diaphragm Material': 'PGL',
                                       'Diaphragm Thickness': '4'}},
 'GSD3SNT4B-NSCP15': {'GSD3SNT4B-NSCP15': {' Flow Rate': 150,
                                           ' Flow Units': 'cc/min',
                                           ' Pressure': 150,
                                           'Diaphragm Material': 'PGL',
                                           'Diaphragm Thickness': '10'}},
 'GSD3SNT4B-NSCP25': {'GSD3SNT4B-NSCP25': {' Flow Rate': 15,
                                           ' Flow Units': 'cc/min',
                                           ' Pressure': 250,
                                           'Diaphragm Material': 'PGL',
                                           'Diaphragm Thickness': '10'}},
 'GSD3SNT4B-NSCP250': {'GSD3SNT4B-NSCP250': {' Flow Rate': 35,
                                             ' Flow Units': 'cc/min',
                                             ' Pressure': 250,
                                             'Diaphragm Material': 'PGL',
                                             'Diaphragm Thickness': '10'}},
 'GSD3SNT4B-NSMP40': {'GSD3SNT4B-NSMP40': {' Flow Rate': 1,
                                           ' Flow Units': 'cc/min',
                                           ' Pressure': 400,
                                           'Diaphragm Material': 'PGL',
                                           'Diaphragm Thickness': '10'}},
 'GSD3SNT4B-NSMP50': {'GSD3SNT4B-NSMP50': {' Flow Rate': 0,
                                           ' Flow Units': 'EQ',
                                           ' Pressure': 500,
                                           'Diaphragm Material': 'Viton',
                                           'Diaphragm Thickness': '23'}},
 'GSD4ANG4B': {'GSD4ANG4B': {' Flow Rate': 175,
                             ' Flow Units': 'cc/min',
                             ' Pressure': 5,
                             'Diaphragm Material': 'Viton',
                             'Diaphragm Thickness': '9'}},
 'GSD4ANG5-': {'GSD4ANG5-': {' Flow Rate': 250,
                             ' Flow Units': 'cc/min',
                             ' Pressure': 5,
                             'Diaphragm Material': 'PTFE (virgin)',
                             'Diaphragm Thickness': '4'}},
 'GSD4SNG4B-': {'GSD4SNG4B-': {' Flow Rate': 75,
                               ' Flow Units': 'cc/min',
                               ' Pressure': 5,
                               'Diaphragm Material': 'Buna',
                               'Diaphragm Thickness': '10'}},
 'GSD4SNG4B-NSCP15': {'GSD4SNG4B-NSCP15': {' Flow Rate': 325,
                                           ' Flow Units': 'cc/min',
                                           ' Pressure': 150,
                                           'Diaphragm Material': 'PGL',
                                           'Diaphragm Thickness': '10'}},
 'GSD4SNG5-N': {'GSD4SNG5-N': {' Flow Rate': 225,
                               ' Flow Units': 'cc/min',
                               ' Pressure': 5,
                               'Diaphragm Material': 'Buna',
                               'Diaphragm Thickness': '10'}},
 'GSD4SNT5-': {'GSD4SNT5-': {' Flow Rate': 250,
                             ' Flow Units': 'cc/min',
                             ' Pressure': 5,
                             'Diaphragm Material': 'PTFE (virgin)',
                             'Diaphragm Thickness': '5'}},
 'GSD4SNT5-NSCP250T': {'GSD4SNT5-NSCP250T': {' Flow Rate': 225,
                                             ' Flow Units': 'cc/min',
                                             ' Pressure': 250,
                                             'Diaphragm Material': 'PGL',
                                             'Diaphragm Thickness': '10'}},
 'GSD4SNT5-NSCP3': {'GSD4SNT5-NSCP3': {' Flow Rate': 240,
                                       ' Flow Units': 'cc/min',
                                       ' Pressure': 30,
                                       'Diaphragm Material': 'PGL',
                                       'Diaphragm Thickness': '5'}},
 'GSD4SNT5-NSCP50': {'GSD4SNT5-NSCP50': {' Flow Rate': 175,
                                         ' Flow Units': 'cc/min',
                                         ' Pressure': 50,
                                         'Diaphragm Material': 'PGL',
                                         'Diaphragm Thickness': '10'}},
 'GSD6ANG5-': {'GSD6ANG5-': {' Flow Rate': 35,
                             ' Flow Units': 'cc/min',
                             ' Pressure': 5,
                             'Diaphragm Material': 'Viton',
                             'Diaphragm Thickness': '9'}},
 'GSD6ANG5-N': {'GSD6ANG5-N': {' Flow Rate': 100,
                               ' Flow Units': 'cc/min',
                               ' Pressure': 5,
                               'Diaphragm Material': 'Buna',
                               'Diaphragm Thickness': '10'}},
 'GSD6PNG5-N': {'GSD6PNG5-N': {' Flow Rate': 1.4,
                               ' Flow Units': '#VALUE!',
                               ' Pressure': 5,
                               'Diaphragm Material': 'Viton',
                               'Diaphragm Thickness': '23'}},
 'GSD6SNG5-': {'GSD6SNG5-': {' Flow Rate': 300,
                             ' Flow Units': 'cc/min',
                             ' Pressure': 5,
                             'Diaphragm Material': 'Viton',
                             'Diaphragm Thickness': '9'}},
 'GSD6SNG5-NSCP100': {'GSD6SNG5-NSCP100': {' Flow Rate': 9,
                                           ' Flow Units': 'cc/min',
                                           ' Pressure': 100,
                                           'Diaphragm Material': 'EPDM',
                                           'Diaphragm Thickness': '20'}},
 'GSD6SNT5-NSCP100': {'GSD6SNT5-NSCP100': {' Flow Rate': 900,
                                           ' Flow Units': 'cc/min',
                                           ' Pressure': 100,
                                           'Diaphragm Material': 'PGL',
                                           'Diaphragm Thickness': '10'}},
 'GSD6SNT5-NSCP300': {'GSD6SNT5-NSCP300': {' Flow Rate': 1,
                                           ' Flow Units': 'L/min',
                                           ' Pressure': 300,
                                           'Diaphragm Material': 'PGL',
                                           'Diaphragm Thickness': '15'}},
 'GSD8ANG4B': {'GSD8ANG4B': {' Flow Rate': 150,
                             ' Flow Units': 'cc/min',
                             ' Pressure': 5,
                             'Diaphragm Material': 'Viton',
                             'Diaphragm Thickness': '9'}},
 'GSD8ANG4B-NA': {'GSD8ANG4B-NA': {' Flow Rate': 90,
                                   ' Flow Units': 'cc/min',
                                   ' Pressure': 3,
                                   'Diaphragm Material': 'PTFE (virgin)',
                                   'Diaphragm Thickness': '3'}},
 'GSD8PNT5-': {'GSD8PNT5-': {' Flow Rate': 750,
                             ' Flow Units': 'cc/min',
                             ' Pressure': 5,
                             'Diaphragm Material': 'PGL',
                             'Diaphragm Thickness': '4'}},
 'GSD8PNT5-N': {'GSD8PNT5-N': {' Flow Rate': 150,
                               ' Flow Units': 'cc/min',
                               ' Pressure': 5,
                               'Diaphragm Material': 'Viton',
                               'Diaphragm Thickness': '23'}},
 'GSD8PNT5-NPC': {'GSD8PNT5-NPC': {' Flow Rate': 1,
                                   ' Flow Units': 'EQ',
                                   ' Pressure': 1,
                                   'Diaphragm Material': 'PTFE (virgin)',
                                   'Diaphragm Thickness': '4'}},
 'GSD8SFT5-NSCP100': {'GSD8SFT5-NSCP100': {' Flow Rate': 500,
                                           ' Flow Units': 'cc/min',
                                           ' Pressure': 100,
                                           'Diaphragm Material': 'PGL',
                                           'Diaphragm Thickness': '10'}},
 'GSD8SNG5-': {'GSD8SNG5-': {' Flow Rate': 70,
                             ' Flow Units': 'cc/min',
                             ' Pressure': 5,
                             'Diaphragm Material': 'Viton',
                             'Diaphragm Thickness': '9'}},
 'GSD8SNG5-N': {'GSD8SNG5-N': {' Flow Rate': 1.2,
                               ' Flow Units': 'L/min',
                               ' Pressure': 5,
                               'Diaphragm Material': 'Viton',
                               'Diaphragm Thickness': '9'}},
 'GSD8SNN5-NSBP350': {'GSD8SNN5-NSBP350': {' Flow Rate': 400,
                                           ' Flow Units': 'cc/min',
                                           ' Pressure': 350,
                                           'Diaphragm Material': 'PGL',
                                           'Diaphragm Thickness': '22'}},
 'GSD8SNT5-NSCP100': {'GSD8SNT5-NSCP100': {' Flow Rate': 750,
                                           ' Flow Units': 'cc/min',
                                           ' Pressure': 100,
                                           'Diaphragm Material': 'PGL',
                                           'Diaphragm Thickness': '10'}},
 'GSD8SNT5-NSCP150': {'GSD8SNT5-NSCP150': {' Flow Rate': 1,
                                           ' Flow Units': 'L/min',
                                           ' Pressure': 150,
                                           'Diaphragm Material': 'PGL',
                                           'Diaphragm Thickness': '10'}},
 'GSD8SNT5-NSCP30': {'GSD8SNT5-NSCP30': {' Flow Rate': 325,
                                         ' Flow Units': 'cc/min',
                                         ' Pressure': 30,
                                         'Diaphragm Material': 'PTFE (virgin)',
                                         'Diaphragm Thickness': '5'}},
 'GSD8SNT5-NSCP50': {'GSD8SNT5-NSCP50': {' Flow Rate': 500,
                                         ' Flow Units': 'cc/min',
                                         ' Pressure': 50,
                                         'Diaphragm Material': 'PGL',
                                         'Diaphragm Thickness': '10'}},
 'GSD8SNT5-NSCP60': {'GSD8SNT5-NSCP60': {' Flow Rate': 1,
                                         ' Flow Units': 'L/min',
                                         ' Pressure': 60,
                                         'Diaphragm Material': 'PGL',
                                         'Diaphragm Thickness': '10'}},
 'GSDH6SNN4B-NSEP1': {'GSDH6SNN4B-NSEP1': {' Flow Rate': 400,
                                           ' Flow Units': 'cc/min',
                                           ' Pressure': 1000,
                                           'Diaphragm Material': 'PEEK',
                                           'Diaphragm Thickness': '20'}},
 'GSDH6SNN5-NSEP150': {'GSDH6SNN5-NSEP150': {' Flow Rate': 10,
                                             ' Flow Units': 'L/min',
                                             ' Pressure': 1500,
                                             'Diaphragm Material': 'SS316',
                                             'Diaphragm Thickness': '10'}},
 'GSDM4SNT5-NSCP50': {'GSDM4SNT5-NSCP50': {' Flow Rate': 1,
                                           ' Flow Units': 'cc/min',
                                           ' Pressure': 500,
                                           'Diaphragm Material': 'PGL',
                                           'Diaphragm Thickness': '10'}},
 'GSDM8SNT4B-NSBP6': {'GSDM8SNT4B-NSBP6': {' Flow Rate': 75,
                                           ' Flow Units': 'cc/min',
                                           ' Pressure': 600,
                                           'Diaphragm Material': 'PGL',
                                           'Diaphragm Thickness': '22'}},
 'H3P0HVN7B-NSBP3000': {'H3P0HVN7B-NSBP3000': {' Flow Rate': 0,
                                               ' Flow Units': 'EQ',
                                               ' Pressure': 3000,
                                               'Diaphragm Material': 'PGL',
                                               'Diaphragm Thickness': '22'}},
 'H3P0SNN8-NSBP200': {'H3P0SNN8-NSBP200': {' Flow Rate': 225,
                                           ' Flow Units': 'cc/min',
                                           ' Pressure': 2000,
                                           'Diaphragm Material': 'SS316',
                                           'Diaphragm Thickness': '5'}},
 'H3P1HNN8-NSBP1500': {'H3P1HNN8-NSBP1500': {' Flow Rate': 0,
                                             ' Flow Units': 'EQ',
                                             ' Pressure': 1500,
                                             'Diaphragm Material': 'PEEK',
                                             'Diaphragm Thickness': '10'}},
 'H3P1HNN8-NSBP3000': {'H3P1HNN8-NSBP3000': {' Flow Rate': 28,
                                             ' Flow Units': 'cc/min',
                                             ' Pressure': 3000,
                                             'Diaphragm Material': 'Hastelloy',
                                             'Diaphragm Thickness': '5'}},
 'H3P1HNN8-NSBP3000T': {'H3P1HNN8-NSBP3000T': {' Flow Rate': 0,
                                               ' Flow Units': 'EQ',
                                               ' Pressure': 3000,
                                               'Diaphragm Material': 'PGL',
                                               'Diaphragm Thickness': '22'}},
 'H3P1SNN8-NSBP1500': {'H3P1SNN8-NSBP1500': {' Flow Rate': 0,
                                             ' Flow Units': 'EQ',
                                             ' Pressure': 1500,
                                             'Diaphragm Material': 'PGL',
                                             'Diaphragm Thickness': '20'}},
 'H3P1SNN8-NSBP1500T': {'H3P1SNN8-NSBP1500T': {' Flow Rate': 0,
                                               ' Flow Units': 'EQ',
                                               ' Pressure': 1500,
                                               'Diaphragm Material': 'PGL',
                                               'Diaphragm Thickness': '15'}},
 'H3P1SNN8-NSBP200': {'H3P1SNN8-NSBP200': {' Flow Rate': 200,
                                           ' Flow Units': 'cc/min',
                                           ' Pressure': 2000,
                                           'Diaphragm Material': 'SS316',
                                           'Diaphragm Thickness': '5'}},
 'H3P1SNN8-NSBP3000': {'H3P1SNN8-NSBP3000': {' Flow Rate': 0,
                                             ' Flow Units': 'EQ',
                                             ' Pressure': 3000,
                                             'Diaphragm Material': 'PGL',
                                             'Diaphragm Thickness': '22'}},
 'H3P2HNN8-NSBP1500': {'H3P2HNN8-NSBP1500': {' Flow Rate': 0,
                                             ' Flow Units': 'EQ',
                                             ' Pressure': 2250,
                                             'Diaphragm Material': 'PEEK',
                                             'Diaphragm Thickness': '10'}},
 'H3P2HNN8-NSBP1500T': {'H3P2HNN8-NSBP1500T': {' Flow Rate': 0,
                                               ' Flow Units': 'EQ',
                                               ' Pressure': 1500,
                                               'Diaphragm Material': 'PGL',
                                               'Diaphragm Thickness': '10'}},
 'H3P2HNN8-NSBP2000T': {'H3P2HNN8-NSBP2000T': {' Flow Rate': 0,
                                               ' Flow Units': 'EQ',
                                               ' Pressure': 2000,
                                               'Diaphragm Material': 'PGL',
                                               'Diaphragm Thickness': '22'}},
 'H3P2SNN8-NSBP1500': {'H3P2SNN8-NSBP1500': {' Flow Rate': 40,
                                             ' Flow Units': 'cc/min',
                                             ' Pressure': 1500,
                                             'Diaphragm Material': 'SS316',
                                             'Diaphragm Thickness': '4'}},
 'H3P2SNN8-NSBP1500T': {'H3P2SNN8-NSBP1500T': {' Flow Rate': 0,
                                               ' Flow Units': 'EQ',
                                               ' Pressure': 2250,
                                               'Diaphragm Material': 'PGL',
                                               'Diaphragm Thickness': '10'}},
 'H3P2SNN8-NSBP2000': {'H3P2SNN8-NSBP2000': {' Flow Rate': 0,
                                             ' Flow Units': 'EQ',
                                             ' Pressure': 2000,
                                             'Diaphragm Material': 'Polyimide',
                                             'Diaphragm Thickness': '8'}},
 'H3P2SNN8-NSBP3000T': {'H3P2SNN8-NSBP3000T': {' Flow Rate': 0,
                                               ' Flow Units': 'EQ',
                                               ' Pressure': 3000,
                                               'Diaphragm Material': 'PEEK',
                                               'Diaphragm Thickness': '20'}},
 'H3PF2SNN8-NSBP1500': {'H3PF2SNN8-NSBP1500': {' Flow Rate': 0,
                                               ' Flow Units': 'EQ',
                                               ' Pressure': 1500,
                                               'Diaphragm Material': 'PGL',
                                               'Diaphragm Thickness': '20'}},
 'H3PF2SNN8-NSBP1500T': {'H3PF2SNN8-NSBP1500T': {' Flow Rate': 0,
                                                 ' Flow Units': 'EQ',
                                                 ' Pressure': 2250,
                                                 'Diaphragm Material': 'PGL',
                                                 'Diaphragm Thickness': '20'}},
 'H3PF2SNN8-NSBP2000': {'H3PF2SNN8-NSBP2000': {' Flow Rate': 12,
                                               ' Flow Units': 'cc/min',
                                               ' Pressure': 2000,
                                               'Diaphragm Material': 'PGL',
                                               'Diaphragm Thickness': '22'}},
 'H6P1SNN8-NSGP6000T': {'H6P1SNN8-NSGP6000T': {' Flow Rate': 0,
                                               ' Flow Units': 'EQ',
                                               ' Pressure': 6000,
                                               'Diaphragm Material': 'PEEK',
                                               'Diaphragm Thickness': '40'}},
 'H6PF2SNN8-NSGP6000': {'H6PF2SNN8-NSGP6000': {' Flow Rate': 0,
                                               ' Flow Units': 'EQ',
                                               ' Pressure': 5000,
                                               'Diaphragm Material': 'PEEK',
                                               'Diaphragm Thickness': '40'}},
 'HF2SNN12-NSMP100': {'HF2SNN12-NSMP100': {' Flow Rate': 900,
                                           ' Flow Units': 'cc/min',
                                           ' Pressure': 1000,
                                           'Diaphragm Material': 'SS316',
                                           'Diaphragm Thickness': '4'}},
 'HF2SNN12-NSMP1000': {'HF2SNN12-NSMP1000': {' Flow Rate': 0,
                                             ' Flow Units': 'EQ',
                                             ' Pressure': 1000,
                                             'Diaphragm Material': 'PGL',
                                             'Diaphragm Thickness': '15'}},
 'HF2SNN12-NSMP500': {'HF2SNN12-NSMP500': {' Flow Rate': 90,
                                           ' Flow Units': 'cc/min',
                                           ' Pressure': 500,
                                           'Diaphragm Material': 'SS316',
                                           'Diaphragm Thickness': '5'}},
 'HF2SNN12B-NSCP1': {'HF2SNN12B-NSCP1': {' Flow Rate': 5,
                                         ' Flow Units': 'cc/min',
                                         ' Pressure': 10,
                                         'Diaphragm Material': 'PTFE (virgin)',
                                         'Diaphragm Thickness': '3'}},
 'HF2SNN12B-NSCP20': {'HF2SNN12B-NSCP20': {' Flow Rate': 0,
                                           ' Flow Units': 'EQ',
                                           ' Pressure': 200,
                                           'Diaphragm Material': 'PGL',
                                           'Diaphragm Thickness': '5'}},
 'HF2SNN12B-NSMP100': {'HF2SNN12B-NSMP100': {' Flow Rate': 35,
                                             ' Flow Units': 'cc/min',
                                             ' Pressure': 290,
                                             'Diaphragm Material': 'PGL',
                                             'Diaphragm Thickness': '4'}},
 'HF2SNN12B-NSMP1000': {'HF2SNN12B-NSMP1000': {' Flow Rate': 0,
                                               ' Flow Units': 'EQ',
                                               ' Pressure': 1000,
                                               'Diaphragm Material': 'PGL',
                                               'Diaphragm Thickness': '15'}},
 'HF2SNN12B-NSMP50': {'HF2SNN12B-NSMP50': {' Flow Rate': 30,
                                           ' Flow Units': 'cc/min',
                                           ' Pressure': 500,
                                           'Diaphragm Material': 'PGL',
                                           'Diaphragm Thickness': '10'}},
 'HF2SNN12B-NSMP500': {'HF2SNN12B-NSMP500': {' Flow Rate': 0,
                                             ' Flow Units': 'EQ',
                                             ' Pressure': 500,
                                             'Diaphragm Material': 'PGL',
                                             'Diaphragm Thickness': '10'}},
 'HF2SNN12B-NSMP700': {'HF2SNN12B-NSMP700': {' Flow Rate': 6,
                                             ' Flow Units': 'cc/min',
                                             ' Pressure': 700,
                                             'Diaphragm Material': 'PGL',
                                             'Diaphragm Thickness': '10'}},
 'HF2SON12-NSMP1000': {'HF2SON12-NSMP1000': {' Flow Rate': 7,
                                             ' Flow Units': 'cc/min',
                                             ' Pressure': 1000,
                                             'Diaphragm Material': 'PTFE - USP '
                                                                   'VI',
                                             'Diaphragm Thickness': '20'}},
 'HT2SNN8-NSEP1000': {'HT2SNN8-NSEP1000': {' Flow Rate': 175,
                                           ' Flow Units': 'cc/min',
                                           ' Pressure': 1000,
                                           'Diaphragm Material': 'SS316',
                                           'Diaphragm Thickness': '4'}},
 'HT2SNN8-NSEP2500T': {'HT2SNN8-NSEP2500T': {' Flow Rate': 13,
                                             ' Flow Units': 'cc/min',
                                             ' Pressure': 2500,
                                             'Diaphragm Material': 'SS316',
                                             'Diaphragm Thickness': '4'}},
 'LF0SVN12B-NSMP1000': {'LF0SVN12B-NSMP1000': {' Flow Rate': 0,
                                               ' Flow Units': 'EQ',
                                               ' Pressure': 1000,
                                               'Diaphragm Material': 'PGL',
                                               'Diaphragm Thickness': '10'}},
 'LF1HNN12B-NSMP100': {'LF1HNN12B-NSMP100': {' Flow Rate': 0,
                                             ' Flow Units': 'EQ',
                                             ' Pressure': 1000,
                                             'Diaphragm Material': 'PGL',
                                             'Diaphragm Thickness': '15'}},
 'LF1HNN12B-NSMP15': {'LF1HNN12B-NSMP15': {' Flow Rate': 3,
                                           ' Flow Units': 'cc/min',
                                           ' Pressure': 150,
                                           'Diaphragm Material': 'PTFE '
                                                                 '(virgin)',
                                           'Diaphragm Thickness': '10'}},
 'LF1HNN12B-NSMP50': {'LF1HNN12B-NSMP50': {' Flow Rate': 0,
                                           ' Flow Units': 'EQ',
                                           ' Pressure': 500,
                                           'Diaphragm Material': 'PGL',
                                           'Diaphragm Thickness': '10'}},
 'LF1SBN12B-BSMP50': {'LF1SBN12B-BSMP50': {' Flow Rate': 7,
                                           ' Flow Units': 'cc/min',
                                           ' Pressure': 500,
                                           'Diaphragm Material': 'SS316',
                                           'Diaphragm Thickness': '4'}},
 'LF1SNN12-NSMP1000': {'LF1SNN12-NSMP1000': {' Flow Rate': 0,
                                             ' Flow Units': 'EQ',
                                             ' Pressure': 1000,
                                             'Diaphragm Material': 'PGL',
                                             'Diaphragm Thickness': '10'}},
 'LF1SNN12-NSMP1000T': {'LF1SNN12-NSMP1000T': {' Flow Rate': 0,
                                               ' Flow Units': 'EQ',
                                               ' Pressure': 1000,
                                               'Diaphragm Material': 'PGL',
                                               'Diaphragm Thickness': '10'}},
 'LF1SNN12-NSMP750T': {'LF1SNN12-NSMP750T': {' Flow Rate': 35,
                                             ' Flow Units': 'cc/min',
                                             ' Pressure': 750,
                                             'Diaphragm Material': 'PGL',
                                             'Diaphragm Thickness': '20'}},
 'LF1SNN12B-NS': {'LF1SNN12B-NS': {' Flow Rate': 0,
                                   ' Flow Units': 'EQ',
                                   ' Pressure': 1,
                                   'Diaphragm Material': 'PTFE (virgin)',
                                   'Diaphragm Thickness': '2'}},
 'LF1SNN12B-NSM': {'LF1SNN12B-NSM': {' Flow Rate': 1,
                                     ' Flow Units': 'cc/min',
                                     ' Pressure': 10,
                                     'Diaphragm Material': 'Polyethylene',
                                     'Diaphragm Thickness': '4'}},
 'LF1SNN12B-NSMP': {'LF1SNN12B-NSMP': {' Flow Rate': 10,
                                       ' Flow Units': 'cc/min',
                                       ' Pressure': 15,
                                       'Diaphragm Material': 'PTFE (virgin)',
                                       'Diaphragm Thickness': '4'}},
 'LF1SNN12B-NSMP1000': {'LF1SNN12B-NSMP1000': {' Flow Rate': 0,
                                               ' Flow Units': 'EQ',
                                               ' Pressure': 1000,
                                               'Diaphragm Material': 'PGL',
                                               'Diaphragm Thickness': '10'}},
 'LF1SNN12B-NSMP1000T': {'LF1SNN12B-NSMP1000T': {' Flow Rate': 0,
                                                 ' Flow Units': 'EQ',
                                                 ' Pressure': 1000,
                                                 'Diaphragm Material': 'PGL',
                                                 'Diaphragm Thickness': '10'}},
 'LF1SNN12B-NSMP150': {'LF1SNN12B-NSMP150': {' Flow Rate': 1,
                                             ' Flow Units': '1 cc/min',
                                             ' Pressure': 150,
                                             'Diaphragm Material': 'PGL',
                                             'Diaphragm Thickness': '10'}},
 'LF1SNN12B-NSMP30': {'LF1SNN12B-NSMP30': {' Flow Rate': 0,
                                           ' Flow Units': 'EQ',
                                           ' Pressure': 300,
                                           'Diaphragm Material': 'PGL',
                                           'Diaphragm Thickness': '10'}},
 'LF1SNN12B-NSMP500': {'LF1SNN12B-NSMP500': {' Flow Rate': 0,
                                             ' Flow Units': 'EQ',
                                             ' Pressure': 500,
                                             'Diaphragm Material': 'PGL',
                                             'Diaphragm Thickness': '10'}},
 'LF1SNN12B-NSMP750': {'LF1SNN12B-NSMP750': {' Flow Rate': 0,
                                             ' Flow Units': 'EQ',
                                             ' Pressure': 750,
                                             'Diaphragm Material': 'PGL',
                                             'Diaphragm Thickness': '10'}},
 'LF2FNN12B-NFC': {'LF2FNN12B-NFC': {' Flow Rate': 12,
                                     ' Flow Units': 'cc/min',
                                     ' Pressure': 30,
                                     'Diaphragm Material': 'PTFE (virgin)',
                                     'Diaphragm Thickness': '5'}},
 'LF2SNN12-NSMP10': {'LF2SNN12-NSMP10': {' Flow Rate': 10,
                                         ' Flow Units': 'cc/min',
                                         ' Pressure': 100,
                                         'Diaphragm Material': 'PGL',
                                         'Diaphragm Thickness': '5'}},
 'LF2SNN12-NSMP1000T': {'LF2SNN12-NSMP1000T': {' Flow Rate': 0,
                                               ' Flow Units': 'EQ',
                                               ' Pressure': 1000,
                                               'Diaphragm Material': 'PGL',
                                               'Diaphragm Thickness': '10'}},
 'LF2SNN12-NSMP500T': {'LF2SNN12-NSMP500T': {' Flow Rate': 0,
                                             ' Flow Units': 'EQ',
                                             ' Pressure': 500,
                                             'Diaphragm Material': 'PGL',
                                             'Diaphragm Thickness': '10'}},
 'LF2SNN12B-NSMP': {'LF2SNN12B-NSMP': {' Flow Rate': 8,
                                       ' Flow Units': 'cc/min',
                                       ' Pressure': 50,
                                       'Diaphragm Material': 'PTFE (virgin)',
                                       'Diaphragm Thickness': '5'}},
 'LF2SNN12B-NSMP1': {'LF2SNN12B-NSMP1': {' Flow Rate': 10,
                                         ' Flow Units': 'cc/min',
                                         ' Pressure': 150,
                                         'Diaphragm Material': 'PGL',
                                         'Diaphragm Thickness': '5'}},
 'LF2SNN12B-NSMP10': {'LF2SNN12B-NSMP10': {' Flow Rate': 0,
                                           ' Flow Units': 'eq',
                                           ' Pressure': 1000,
                                           'Diaphragm Material': 'Polyimide',
                                           'Diaphragm Thickness': '5'}},
 'LF2SNN12B-NSMP100': {'LF2SNN12B-NSMP100': {' Flow Rate': 1,
                                             ' Flow Units': 'cc/min',
                                             ' Pressure': 100,
                                             'Diaphragm Material': 'PGL',
                                             'Diaphragm Thickness': '4'}},
 'LF2SNN12B-NSMP1000': {'LF2SNN12B-NSMP1000': {' Flow Rate': 0,
                                               ' Flow Units': 'EQ',
                                               ' Pressure': 1000,
                                               'Diaphragm Material': 'PGL',
                                               'Diaphragm Thickness': '10'}},
 'LF2SNN12B-NSMP2': {'LF2SNN12B-NSMP2': {' Flow Rate': 0,
                                         ' Flow Units': 'EQ',
                                         ' Pressure': 200,
                                         'Diaphragm Material': 'PGL',
                                         'Diaphragm Thickness': '4'}},
 'LF2SNN12B-NSMP20': {'LF2SNN12B-NSMP20': {' Flow Rate': 6,
                                           ' Flow Units': 'cc/min',
                                           ' Pressure': 200,
                                           'Diaphragm Material': 'PGL',
                                           'Diaphragm Thickness': '5'}},
 'LF2SNN12B-NSMP25': {'LF2SNN12B-NSMP25': {' Flow Rate': 1,
                                           ' Flow Units': 'cc/min',
                                           ' Pressure': 250,
                                           'Diaphragm Material': 'PGL',
                                           'Diaphragm Thickness': '10'}},
 'LF2SNN12B-NSMP500': {'LF2SNN12B-NSMP500': {' Flow Rate': 0,
                                             ' Flow Units': 'EQ',
                                             ' Pressure': 500,
                                             'Diaphragm Material': 'PGL',
                                             'Diaphragm Thickness': '10'}},
 'LF2SON12-NSMP1000': {'LF2SON12-NSMP1000': {' Flow Rate': 0,
                                             ' Flow Units': 'EQ',
                                             ' Pressure': 1000,
                                             'Diaphragm Material': 'PTFE - USP '
                                                                   'VI',
                                             'Diaphragm Thickness': '20'}},
 'LF2SRN12B-NSMP': {'LF2SRN12B-NSMP': {' Flow Rate': 5,
                                       ' Flow Units': 'cc/min',
                                       ' Pressure': 15,
                                       'Diaphragm Material': 'PTFE (virgin)',
                                       'Diaphragm Thickness': '4'}},
 'LF2ZNN12-NSMP1000': {'LF2ZNN12-NSMP1000': {' Flow Rate': 150,
                                             ' Flow Units': 'cc/min',
                                             ' Pressure': 1000,
                                             'Diaphragm Material': 'Hastelloy',
                                             'Diaphragm Thickness': '3'}},
 'LVF0HVN0-NSMP1500': {'LVF0HVN0-NSMP1500': {' Flow Rate': 0,
                                             ' Flow Units': 'EQ',
                                             ' Pressure': 1500,
                                             'Diaphragm Material': 'PGL',
                                             'Diaphragm Thickness': '10'}},
 'LVF0SVN0-NSMP1000': {'LVF0SVN0-NSMP1000': {' Flow Rate': 0,
                                             ' Flow Units': 'EQ',
                                             ' Pressure': 1000,
                                             'Diaphragm Material': 'PGL',
                                             'Diaphragm Thickness': '10'}},
 'LVF0SVN0-NSMP200': {'LVF0SVN0-NSMP200': {' Flow Rate': 0,
                                           ' Flow Units': 'EQ',
                                           ' Pressure': 200,
                                           'Diaphragm Material': 'PGL',
                                           'Diaphragm Thickness': '5'}},
 'LVF0SVN0-NSMP2000T': {'LVF0SVN0-NSMP2000T': {' Flow Rate': 0,
                                               ' Flow Units': 'EQ',
                                               ' Pressure': 2000,
                                               'Diaphragm Material': 'PGL',
                                               'Diaphragm Thickness': '10'}},
 'LVF0SVN0-VSMP10': {'LVF0SVN0-VSMP10': {' Flow Rate': 9,
                                         ' Flow Units': 'cc/min',
                                         ' Pressure': 100,
                                         'Diaphragm Material': 'PGL',
                                         'Diaphragm Thickness': '4'}},
 'U10L1HNN8-NSJP1000': {'U10L1HNN8-NSJP1000': {' Flow Rate': 0,
                                               ' Flow Units': '#VALUE!',
                                               ' Pressure': 5000,
                                               'Diaphragm Material': 'Hastelloy',
                                               'Diaphragm Thickness': '10'}},
 'U10L1HNN8-NSJP10000': {'U10L1HNN8-NSJP10000': {' Flow Rate': 0,
                                                 ' Flow Units': '#VALUE!',
                                                 ' Pressure': 5000,
                                                 'Diaphragm Material': 'PEEK',
                                                 'Diaphragm Thickness': '40'}},
 'U10L1HWN8-WSJP1000': {'U10L1HWN8-WSJP1000': {' Flow Rate': 0,
                                               ' Flow Units': 'EQ',
                                               ' Pressure': 10000,
                                               'Diaphragm Material': 'PEEK',
                                               'Diaphragm Thickness': '40'}},
 'U10L1SNN8-NSJP1000': {'U10L1SNN8-NSJP1000': {' Flow Rate': 0,
                                               ' Flow Units': 'EQ',
                                               ' Pressure': 5000,
                                               'Diaphragm Material': 'PEEK',
                                               'Diaphragm Thickness': '40'}},
 'U10L1SNN8-NSJP10000': {'U10L1SNN8-NSJP10000': {' Flow Rate': 0,
                                                 ' Flow Units': 'EQ',
                                                 ' Pressure': 5000,
                                                 'Diaphragm Material': 'PEEK',
                                                 'Diaphragm Thickness': '40'}},
 'U3L0SNN8-NSBP1000T1': {'U3L0SNN8-NSBP1000T1': {' Flow Rate': 0,
                                                 ' Flow Units': 'EQ',
                                                 ' Pressure': 1000,
                                                 'Diaphragm Material': 'PGL',
                                                 'Diaphragm Thickness': '20'}},
 'U3L0SNN8-NSBP1500T1': {'U3L0SNN8-NSBP1500T1': {' Flow Rate': 0,
                                                 ' Flow Units': 'EQ',
                                                 ' Pressure': 1500,
                                                 'Diaphragm Material': 'PEEK',
                                                 'Diaphragm Thickness': '15'}},
 'U3L0SVN8-NSBP1000': {'U3L0SVN8-NSBP1000': {' Flow Rate': 0,
                                             ' Flow Units': 'EQ',
                                             ' Pressure': 1000,
                                             'Diaphragm Material': 'Polyimide',
                                             'Diaphragm Thickness': '8'}},
 'U3L0SVN8-NSBP250T': {'U3L0SVN8-NSBP250T': {' Flow Rate': 0,
                                             ' Flow Units': 'eq',
                                             ' Pressure': 250,
                                             'Diaphragm Material': 'PGL',
                                             'Diaphragm Thickness': '5'}},
 'U3L0SVN8-NSBP500T': {'U3L0SVN8-NSBP500T': {' Flow Rate': 0,
                                             ' Flow Units': 'EQ',
                                             ' Pressure': 500,
                                             'Diaphragm Material': 'Polyimide',
                                             'Diaphragm Thickness': '5'}},
 'U3L1SNN8-NSBP1500T1': {'U3L1SNN8-NSBP1500T1': {' Flow Rate': 0,
                                                 ' Flow Units': 'EQ',
                                                 ' Pressure': 1500,
                                                 'Diaphragm Material': 'PGL',
                                                 'Diaphragm Thickness': '20'}},
 'U3L1SNN8-NSBP2500T': {'U3L1SNN8-NSBP2500T': {' Flow Rate': 10,
                                               ' Flow Units': 'cc/min',
                                               ' Pressure': 2500,
                                               'Diaphragm Material': 'SS316',
                                               'Diaphragm Thickness': '5'}},
 'U3L1SNN8-NSBP2500T1': {'U3L1SNN8-NSBP2500T1': {' Flow Rate': 0,
                                                 ' Flow Units': 'EQ',
                                                 ' Pressure': 2500,
                                                 'Diaphragm Material': 'PGL',
                                                 'Diaphragm Thickness': '20'}},
 'U3L1SNN8-NSBP500': {'U3L1SNN8-NSBP500': {' Flow Rate': 7,
                                           ' Flow Units': 'cc/min',
                                           ' Pressure': 500,
                                           'Diaphragm Material': 'SS316',
                                           'Diaphragm Thickness': '4'}},
 'U3L2SNN8-NSBP3000T1': {'U3L2SNN8-NSBP3000T1': {' Flow Rate': 0,
                                                 ' Flow Units': 'EQ',
                                                 ' Pressure': 3000,
                                                 'Diaphragm Material': 'PEEK',
                                                 'Diaphragm Thickness': '20'}},
 'U6L1SNN8-NSGP5000T': {'U6L1SNN8-NSGP5000T': {' Flow Rate': 0,
                                               ' Flow Units': 'EQ',
                                               ' Pressure': 5000,
                                               'Diaphragm Material': 'Polyimide',
                                               'Diaphragm Thickness': '20'}},
 'U6L1SNN8-NSGP5000T1': {'U6L1SNN8-NSGP5000T1': {' Flow Rate': 0,
                                                 ' Flow Units': 'EQ',
                                                 ' Pressure': 5000,
                                                 'Diaphragm Material': 'PEEK',
                                                 'Diaphragm Thickness': '40'}},
 'U6L1SNN8-NSGP6000T': {'U6L1SNN8-NSGP6000T': {' Flow Rate': 0,
                                               ' Flow Units': 'EQ',
                                               ' Pressure': 6000,
                                               'Diaphragm Material': 'SS316',
                                               'Diaphragm Thickness': '8'}},
 'U6L1SNN8-NSGP6000T1': {'U6L1SNN8-NSGP6000T1': {' Flow Rate': 0,
                                                 ' Flow Units': 'EQ',
                                                 ' Pressure': 5000,
                                                 'Diaphragm Material': 'Polyimide',
                                                 'Diaphragm Thickness': '20'}},
 'U6L2SNN8-NSGP6000T1': {'U6L2SNN8-NSGP6000T1': {' Flow Rate': 0,
                                                 ' Flow Units': 'EQ',
                                                 ' Pressure': 5000,
                                                 'Diaphragm Material': 'PEEK',
                                                 'Diaphragm Thickness': '40'}},
 'ZF0HVN8-NSBP2500T1': {'ZF0HVN8-NSBP2500T1': {' Flow Rate': 0,
                                               ' Flow Units': 'EQ',
                                               ' Pressure': 2500,
                                               'Diaphragm Material': 'Hastelloy',
                                               'Diaphragm Thickness': '5'}},
 'ZF0SNN8-NSBP1000T10': {'ZF0SNN8-NSBP1000T10': {' Flow Rate': 0,
                                                 ' Flow Units': '#VALUE!',
                                                 ' Pressure': 1000,
                                                 'Diaphragm Material': 'SS316',
                                                 'Diaphragm Thickness': '4'}},
 'ZF0SVN8-NSBP200T150': {'ZF0SVN8-NSBP200T150': {' Flow Rate': 0,
                                                 ' Flow Units': 'EQ',
                                                 ' Pressure': 200,
                                                 'Diaphragm Material': 'PGL',
                                                 'Diaphragm Thickness': '10'}},
 'ZF0SVN8-NSBP200T20': {'ZF0SVN8-NSBP200T20': {' Flow Rate': 0,
                                               ' Flow Units': 'EQ',
                                               ' Pressure': 200,
                                               'Diaphragm Material': 'SS316',
                                               'Diaphragm Thickness': '4'}},
 'ZF0SVN8-NSBP250T150': {'ZF0SVN8-NSBP250T150': {' Flow Rate': 0,
                                                 ' Flow Units': 'EQ',
                                                 ' Pressure': 250,
                                                 'Diaphragm Material': 'PGL',
                                                 'Diaphragm Thickness': '10'}},
 'ZF0SVN8-NSBP750T20': {'ZF0SVN8-NSBP750T20': {' Flow Rate': 0,
                                               ' Flow Units': 'EQ',
                                               ' Pressure': 750,
                                               'Diaphragm Material': 'SS316',
                                               'Diaphragm Thickness': '4'}},
 'ZF1HWN8-NSBP2000T30': {'ZF1HWN8-NSBP2000T30': {' Flow Rate': 0,
                                                 ' Flow Units': 'EQ',
                                                 ' Pressure': 2000,
                                                 'Diaphragm Material': 'Hastelloy',
                                                 'Diaphragm Thickness': '5'}},
 'ZF1SNN8-NSBP1000T3': {'ZF1SNN8-NSBP1000T3': {' Flow Rate': 0,
                                               ' Flow Units': 'EQ',
                                               ' Pressure': 1000,
                                               'Diaphragm Material': 'SS316',
                                               'Diaphragm Thickness': '4'}},
 'ZF1SNN8-NSBP1000T30': {'ZF1SNN8-NSBP1000T30': {' Flow Rate': 0,
                                                 ' Flow Units': 'EQ',
                                                 ' Pressure': 1000,
                                                 'Diaphragm Material': 'SS316',
                                                 'Diaphragm Thickness': '4'}},
 'ZF1SNN8-NSBP1500T30': {'ZF1SNN8-NSBP1500T30': {' Flow Rate': 0,
                                                 ' Flow Units': 'EQ',
                                                 ' Pressure': 1500,
                                                 'Diaphragm Material': 'SS316',
                                                 'Diaphragm Thickness': '4'}},
 'ZF1SNN8-NSBP2000T100': {'ZF1SNN8-NSBP2000T100': {' Flow Rate': 0,
                                                   ' Flow Units': 'EQ',
                                                   ' Pressure': 2000,
                                                   'Diaphragm Material': 'PGL',
                                                   'Diaphragm Thickness': '22'}},
 'ZF1SNN8-NSBP2000T3': {'ZF1SNN8-NSBP2000T3': {' Flow Rate': 0,
                                               ' Flow Units': 'EQ',
                                               ' Pressure': 2000,
                                               'Diaphragm Material': 'SS316',
                                               'Diaphragm Thickness': '4'}},
 'ZF1SNN8-NSBP250T200': {'ZF1SNN8-NSBP250T200': {' Flow Rate': 0,
                                                 ' Flow Units': '#VALUE!',
                                                 ' Pressure': 250,
                                                 'Diaphragm Material': 'SS316',
                                                 'Diaphragm Thickness': '5'}},
 'ZF1SNN8-NSBP3000T2': {'ZF1SNN8-NSBP3000T2': {' Flow Rate': 0,
                                               ' Flow Units': 'EQ',
                                               ' Pressure': 3000,
                                               'Diaphragm Material': 'SS316',
                                               'Diaphragm Thickness': '6'}},
 'ZF1SNN8-NSBP750T10': {'ZF1SNN8-NSBP750T10': {' Flow Rate': 0,
                                               ' Flow Units': 'EQ',
                                               ' Pressure': 750,
                                               'Diaphragm Material': 'PGL',
                                               'Diaphragm Thickness': '10'}},
 'ZF1SWN4B-NSBP3000T': {'ZF1SWN4B-NSBP3000T': {' Flow Rate': 0,
                                               ' Flow Units': '#VALUE!',
                                               ' Pressure': 3000,
                                               'Diaphragm Material': 'Hastelloy',
                                               'Diaphragm Thickness': '5'}}}